language: go

go:
  - 1.16.x
  - tip

sudo: false

install:
  - go get golang.org/x/tools/cmd/cover
  - go install github.com/mattn/goveralls@latest
  - go get

script:
  - echo "TRAVIS_GO_VERSION=${TRAVIS_GO_VERSION}"
  - go test -v -covermode=count -coverprofile=coverage.out ./...
  - $GOPATH/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN

env:
  global:
    - GO111MODULE=on
