language: go

go:
  - 1.13.x
  - tip

sudo: false

install:
  - go get golang.org/x/tools/cmd/cover
  - if [ $TRAVIS_GO_VERSION =~ ^1\.12 ]; then go get github.com/mattn/goveralls; else go install github.com/mattn/goveralls@latest; fi

script:
  - go test -v -covermode=count -coverprofile=coverage.out ./...
  - $GOPATH/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN

env:
  global:
    - GO111MODULE=on
